#!/usr/bin/env sh

set -eu

if [ -n "${SWAGGER_CMD+1}" ]
then
    echo "Using Swagger command \`${SWAGGER_CMD}\`."
else
    if ! which openapi-generator
    then
        echo "openapi-generator is either not installed on this system or is"\
            "unavailable through the \$PATH."
        while true; do
            printf "Install it from Homebrew now? [y/N] "
            read -r  yn
            case "$yn" in
                [Yy]* ) break;;
                [Nn]* ) exit;;
                '' ) exit;;
            esac
        done

        echo "Updating Homebrew and then installing openapi-generator"
        brew update
        brew install openapi-generator
    fi

    SWAGGER_CMD="openapi-generator"
fi


languages=$(ls swagger-templates)

for lang in $languages
do
    $SWAGGER_CMD generate \
        --input-spec "./swagger.json" \
        --generator-name "${lang}" \
        --config "./swagger-config/config-${lang}.json" \
        --template-dir "./swagger-templates/${lang}" \
        --output "./swagger-out/${lang}"
done
